Chore(Ref): Add some minor changes & Refactor the code
RobertCraigie/prisma-client-py pull request #194
Opened 2021-12-24 17:45 UTC by yezz123

Most refactoring cases were Replacing conditional assignment to a variable with an if expression.

2021-12-24 18:01 UTC, RobertCraigie commented
Before I do a full review, is there any underlying reason behind one-lining if statements or is it personal style preference?

2021-12-24 18:16 UTC, RobertCraigie requested changes
Thanks for the contribution!

2021-12-24 18:16 UTC, RobertCraigie commented on tests/utils.py
> +    delta = dt1 - dt2 if dt1 > dt2 else dt2 - dt1
I find this more difficult to read, please revert this back to the original.

2021-12-24 18:16 UTC, RobertCraigie commented on src/prisma/generator/models.py
> +            raise ValueError(f'Unsupported scalar field type: {type_}')
I prefer the original style as it makes it easier to add more cases in the future.

For example, if we needed to add another check for scalar types then with the old style we would just have to add a new nested if statement, however with this new style we will either have to duplicate the `kind == 'scalar'` check or extract it to it's own if statement, bringing the code back to its original state.

2021-12-24 18:16 UTC, RobertCraigie commented on src/prisma/generator/errors.py
> +        annotation = '@@id' if isinstance(constraint, PrimaryKey) else '@@unique'
See comment on `src/prisma/generator/models.py`.

2021-12-24 18:16 UTC, RobertCraigie commented on src/prisma/mypy.py
> +                )  # pylint: disable=no-member
See comment on src/prisma/generator/models.py.

It also localises our lint comment which I prefer.

2022-01-01 15:58 UTC, yezz123 commented
Hello @RobertCraigie, Sorry I miss checking the notification in GitHub and PRs that I Open I Just checked this while I was having a lot of works during these days, If we can enhance anything I can help!

Also I'm, working in a PR to Add Prisma-Client to AuthX

2022-01-01 17:23 UTC, RobertCraigie commented
@yezz123 no worries! 

> Also I'm, working in a PR to Add Prisma-Client to AuthX

I'm more than happy to help! Let me know if you have any questions and I'm happy to look over the code when you're finished :)

2022-01-01 17:26 UTC, yezz123 commented
> @yezz123 no worries!
> 
> > Also I'm, working in a PR to Add Prisma-Client to AuthX
> 
> I'm more than happy to help! Let me know if you have any questions and I'm happy to look over the code :)

Yes, Lately in FastAPI server a developer asked about adding Prisma-Client Support and I see its time to do it, while i just drop out MongoDB and Add SQL Databases, i Will add Prisma also

2022-01-01 17:35 UTC, RobertCraigie commented
Exciting! Prisma also supports MongoDB.

2022-01-02 12:58 UTC, RobertCraigie approved these changes

2022-01-02 12:58 UTC, merged

2022-01-02 12:58 UTC, RobertCraigie commented
Thank you!