Refactor/client
RobertCraigie/prisma-client-py pull request #277
Opened 2022-02-07 03:37 UTC by kivo360

## Change Summary

Please summarise the changes this pull request is making here.

## Checklist

- [x] Unit tests for the changes exist
- [x] Tests pass without significant drop in coverage
- [x] Documentation reflects changes where applicable
- [x] Test snapshots have been [updated](https://prisma-client-py.readthedocs.io/en/latest/contributing/contributing/#snapshot-tests) if applicable

## Agreement

By submitting this pull request, I confirm that you can use, modify, copy and redistribute this contribution, under the terms of your choice.

2022-02-14 17:25 UTC, kivo360 commented
Mind merging this in?

2022-02-14 19:17 UTC, RobertCraigie requested changes
Just a lot of minor nitpicks :)

You'll have to update the snapshots again unfortunately

2022-02-14 19:17 UTC, RobertCraigie commented on src/prisma/utils.py
> +MAX_FN_SIGNATURE = 90
```suggestion
```

2022-02-14 19:17 UTC, RobertCraigie commented on src/prisma/generator/templates/client.py.jinja
> +Client = Prisma
```suggestion
Client = Prisma

```

2022-02-14 19:17 UTC, RobertCraigie commented on src/prisma/generator/templates/client.py.jinja
> +from . import types, models, errors, actions, utils
```suggestion
from . import types, models, errors, actions
```

2022-02-14 19:17 UTC, RobertCraigie commented on mypy.ini
> +cache_fine_grained=True
```suggestion
cache_fine_grained = True
```

2022-02-14 19:17 UTC, RobertCraigie commented on src/prisma/__init__.py
> +
```suggestion
```

2022-02-14 19:17 UTC, RobertCraigie commented on src/prisma/__init__.py
> +
```suggestion
    )
```

2022-02-17 18:40 UTC, kivo360 commented
What happened here? I just saw the tests didn't pass.

2022-02-17 18:55 UTC, RobertCraigie commented
@kivo360 I don't know, I've made some refactoring changes so that the `http.py` file is only available post-generation. Try merging main into your branch and see if it fixes the tests.

2022-02-21 19:42 UTC, RobertCraigie approved these changes

2022-02-22 21:44 UTC, merged