fix(requirements): set minimum pydantic version to 1.10.13
RobertCraigie/prisma-client-py pull request #882
Opened 2024-01-25 18:05 UTC by ezorita

## Change Summary

Updated the minimum version of pydantic to `1.10.13`. Current version is set to `1.8.0` but it lacks some required typing extensions.

## Reproduce

Run:
```
pip3 install pydantic==1.8.0 prisma
python3 -c 'import prisma'
```

Output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ezorita/tmp/prisma-pydantic/lib/python3.8/site-packages/prisma/__init__.py", line 11, in <module>
    from ._config import config as config
  File "/home/ezorita/tmp/prisma-pydantic/lib/python3.8/site-packages/prisma/_config.py", line 12, in <module>
    from ._compat import (
  File "/home/ezorita/tmp/prisma-pydantic/lib/python3.8/site-packages/prisma/_compat.py", line 162, in <module>
    from pydantic.typing import is_union as is_union
ImportError: cannot import name 'is_union' from 'pydantic.typing' (/home/ezorita/tmp/prisma-pydantic/lib/python3.8/site-packages/pydantic/typing.cpython-38-x86_64-linux-gnu.so)
```

## Checklist

Should not a a
- [x] Unit tests for the changes exist
- [x] Tests pass without significant drop in coverage
- [x] Documentation reflects changes where applicable
- [ ] Test snapshots have been [updated](https://prisma-client-py.readthedocs.io/en/latest/contributing/contributing/#snapshot-tests) if applicable

## Agreement

By submitting this pull request, I confirm that you can use, modify, copy and redistribute this contribution, under the terms of your choice.

2024-01-25 18:06 UTC, ezorita commented
btw @RobertCraigie hi again! And thanks for the excellent work you're doing with this client, I love it!

2024-01-25 18:12 UTC, RobertCraigie commented
Thanks @ezorita! I appreciate it :)

2024-01-25 18:13 UTC, RobertCraigie requested changes
I think this is very slightly over-restrictive, just ran the tests with `1.10.0` and that also seems to work so I'd prefer to bump our minimum to that - thanks for fixing this!

(also sorry about the flaky test)

2024-01-25 21:26 UTC, RobertCraigie approved these changes
I've lowered the version slightly myself as to not use up more of your time, thanks for bringing this to my attention and opening a PR!

2024-01-25 21:35 UTC, merged

2024-01-26 09:37 UTC, ezorita commented
> I've lowered the version slightly myself as to not use up more of your time, thanks for bringing this to my attention and opening a PR!

my pleasure!